### ISSUE TITLE
GNOME 3.34 - Not working

### ISSUE THREAD

**Issue by TheRoarkster** [petres/gnome-shell-extension-extensions#19]
Hey, hope it is easy to update this for 3.34.  Are you still updating this extension?

**Comment by kebeda** [comment]
I get `TypeError: can't convert undefined to object` when trying to install this on Fedora 31/Gnome 3.34.

**Comment by henrik-wittenberg** [comment]
Not working on Manjaro with Gnome Version 3.34.1

**Comment by rifkiaz** [comment]
Not working on openSUSE Tumbleweed with Gnome Version 3.34.1

**Comment by petres** [comment]
Sorry for the delay, should work on gnome  after commit 6053563a0c67587f70427f33b600f4a880e733dc
