### ISSUE TITLE
[Feature Request] Move to main menu

### ISSUE THREAD

**Issue by cra0zy** [petres/gnome-shell-extension-extensions#2]
I think it would be much nicer that instead of having a separate icon for extension, you moved to the main settings menu.

**Comment by petres** [comment]
Will work on it! Maybe as an option. Do you have an example extension, which uses the main settings menu like you are expecting it?

**Comment by cra0zy** [comment]
> Do you have an example extension, which uses the main settings menu like you are expecting it?

Sorry, I don't have an example extension, but I can describe it. The idea is just to move the current menu to an "Extensions" expandable option under main menu which reveals it.

**Comment by petres** [comment]
an extra point, like WLAN settings, or battery power?

**Comment by cra0zy** [comment]
> an extra point, like WLAN settings, or battery power?

I think yes, I am running GNOME from desktop so not 100% sure. Anyway this:
![untitled](https://cloud.githubusercontent.com/assets/6773302/15585399/551f0344-237f-11e6-935e-90aa2ad81686.png)

**Comment by Armadill0** [comment]
Examples for extensions using the menu:
* https://extensions.gnome.org/extension/55/media-player-indicator/
* https://extensions.gnome.org/extension/130/advanced-settings-in-usermenu/ (although not Gnome 3.20 compatible)

**Comment by petres** [comment]
Added in commit: https://github.com/petres/gnome-shell-extension-extensions/commit/93bac9f72c919a884df1d22d3e3111819d183110
