### ISSUE TITLE
Still not working on GNOME 3.34.1 on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by rifkiaz** [petres/gnome-shell-extension-extensions#20]
Halo this extension still not working on GNOME 3.34.1 on openSUSE Tumbleweed
![Screenshot from 2019-10-29 09-18-54](https://user-images.githubusercontent.com/23344569/67732236-3fa8a500-fa2d-11e9-81e0-81de9f2fa8e7.png)
![Screenshot from 2019-10-29 09-19-25](https://user-images.githubusercontent.com/23344569/67732244-459e8600-fa2d-11e9-9949-11803745ac9a.png)

**Comment by petres** [comment]
how did you install this extension? via extensions.gnome.org? if, there is still a review process open, therefore the fix is currently not available there

**Comment by sheepdestroyer** [comment]
fedora 31, installed from extensions.gnome.org
I did the update from today, still showed as ERROR
I did uninstall then reinstalled : still ERROR

**Comment by petres** [comment]
ok, i have observed the same behaviour, seems like extensions with errors are somehow still loaded. adding another panel entry with same id causes an error.

**Comment by rifkiaz** [comment]
oke, thanks. Fixed!
